job/urls.py
from django.urls import path
from . import views
from . import api



app_name= 'job'

urlpatterns = [

     # api

    path('jobs_api/all',api.JobApi.as_view()),
    path('job_api/<int:pk>',api.JobDetailApi.as_view()),


    path('',views.job_list,name='job-list'),
   
    path('<slug:slug>/',views.job_detail,name='job-detail'),

     path('add_job',views.add_job,name='add-job'),

    

    
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
...
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)



urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('',include('settings.urls')),


    path('blog/',include('blog.urls')),

    path('job/',include('job.urls')),

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),



    path('summernote/', include('django_summernote.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify


JOB_TYPE=[
    ('Full Time','Full Time'),
    ('Part Time','Part Time')
    ]

class Job(models.Model):
    user=models.ForeignKey(User,related_name='job_user',on_delete=models.CASCADE)
    title=models.CharField(max_length=120)
    job_type=models.CharField(max_length=100,choices=JOB_TYPE)
    descriptions=models.TextField(max_length=5000)
    publish_date=models.DateTimeField(default=timezone.now)
    vacany=models.IntegerField()
    salary=models.FloatField()
    experience=models.IntegerField()
    image=models.ImageField(upload_to='photo_job')
    slug=models.SlugField(null=True,blank=True)
    category=models.ForeignKey('Category',related_name='job_category',on_delete=models.SET_NULL,null=True,blank=True)
    location=models.ForeignKey('Location',related_name='job_location',on_delete=models.SET_NULL,null=True,blank=True)


    def __str__(self):
        return self.title
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(Job,self).save(*args,**kwargs)



class Category(models.Model):
    name=models.CharField(max_length=120)

    def __str__(self):
        return self.name
    
class Location(models.Model):
    city=models.CharField(max_length=120)

    def __str__(self):
        return self.city
    
class ApplyUser(models.Model):
    user=models.ForeignKey(User,related_name='apply_user',on_delete=models.CASCADE)
    job=models.ForeignKey(Job,related_name='apply_job',on_delete=models.CASCADE)
    name=models.CharField(max_length=120)
    email=models.CharField(max_length=75)
    website=models.URLField(null=True,blank=True)
    image=models.ImageField(upload_to='image')
    cv=models.FileField(upload_to='cv')
    content=models.TextField(max_length=1500)
    created_at=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

job/forms.py
from django import forms
from .models import Job,ApplyUser

class JobForm(forms.ModelForm):
    class Meta:
        model=Job
        # fields='__all__'
        fields=['job_type','title','descriptions','vacany','salary','experience','image','category','location']
        # exclude=['user','slug','publish_date','title']

class ApplyForm(forms.ModelForm):
    class Meta:
        model=ApplyUser
        # fields='__all__'
        exclude=('user','created_at','job')

job/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .myfilter import JobFilter
from .models import Job
from .forms import JobForm,ApplyForm
from django.contrib.auth.decorators import login_required

from .models import Job
from django.core.paginator import Paginator

@login_required
def job_list(request):
    jobs=Job.objects.all().order_by('-id')
    jobs_recent=Job.objects.all().order_by('-id')[:5]
    jobs_count=Job.objects.all().count()

    myfilter=JobFilter(request.GET,queryset=jobs)
    jobs=myfilter.qs




    paginator = Paginator(jobs, 5)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context={
        'jobs':page_obj,
        'myfilter':myfilter,
        'jobs_count':jobs_count,
        'jobs_recent':jobs_recent
    }
    return render(request,'job/job_list.html',context)

@login_required
def job_detail(request,slug):
    job=Job.objects.get(slug=slug)
    
    if request.method == 'POST':
        form=ApplyForm(request.POST,request.FILES)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.user=request.user
            myform.job=job
            myform.save()
            return redirect(f'/job/{slug}')
    else:
        form=ApplyForm()

    

    context={
        'job':job,
        'form':form
    }
    return render(request,'job/job_detail.html',context)
@login_required
def add_job(request):
    
    if request.method == 'POST':
        form=JobForm(request.POST,request.FILES)
        if form.is_valid():
            form=form.save(commit=False)
            form.user=request.user
            form.save()
            return redirect('/job/')
    else:
           form=JobForm()
    
    return render(request,'job/add_job.html',{'form':form})

job/templates/job/add_job.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block body %}
        <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->
    <div class="container">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
              {% bootstrap_form form %}
                               <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Add Job</button>
                                    </div>
                                </div>
        </form>
    </div>
{% endblock body %}
    

job/templates/job/job_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
       <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    
                                    <!-- {% if image %}
                                        <img src="{{job.image.url}}" alt="">
                                    {% endif %} -->
                                        
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.location.city}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.descriptions|truncatewords:50|safe}}</p>
                        </div>
                     
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form action="#" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                           

                                {% bootstrap_form form %}

                                <div class="col-md-12">
                                    <div class="submit_btn">
                                        <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                                    </div>
                                </div>
                          
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>12 Nov, 2019</span></li>
                                <li>Vacancy: <span>2 Position</span></li>
                                <li>Salary: <span>50k - 120k/y</span></li>
                                <li>Location: <span>California, USA</span></li>
                                <li>Job Nature: <span> Full-time</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}
    

job/templates/job/job_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
      <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{jobs_count}}  Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form action="#" method="get">
                                <div class="row">
                                   
                                    {% bootstrap_form myfilter.form %}
                                    <input type="submit" value="Reset" class="boxed-btn3 w-100">
                               
                                </div>
                            </form>
                        </div>
                    
                     
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>


                              <div class="col-md-6">
                                        <div class="serch_cat d-flex justify-content-end">
                                            <select id="job-select" class="form-select">
                                                <option disabled selected>اختر وظيفة</option>
                                                {% for object in jobs_recent %}
                                                    <option value="{% url 'job:job-detail' object.slug %}">{{ object }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                            </div>


                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                        
                        {% for object in jobs  %}
                            
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{object.image.url}}" alt="" style="width: 120px; height: auto;">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'job:job-detail' object.slug %}"><h4>{{object.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> {{object.location.city}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{object.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'job:job-detail' object.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{object.publish_date|date:'d-M-Y'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>

                         {% endfor %}
                          
                        </div>

                    
                    {% if jobs.has_other_pages %}
               
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">


                                    <ul>
                                    
                                    {% if jobs.has_previous %}
                                       <li><a href="?page={{jobs.previous.page_number}}"> <i class="ti-angle-left"></i> </a></li>  
                                    {% endif %}
                                        

                                       

                                    
                                    {% for i in jobs.paginator.page_range %}
                                        
                                        {% if i >= jobs.number|add:'-3' and i <= jobs.number|add:'3' %}
                                               <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endif %}
                                            
                                         
                                    {% endfor %}
                                        
                                        
                                       

                                    
                                    {% if jobs.has_next %}
                                        <li><a href="?page={{jobs.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>

                                    {% endif %}
                                        
                                        


                                    </ul>
                                </div>
                            </div>
                        </div>

                     
                             
                    {% endif %}
                        



                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

                      <script>
                                document.getElementById("job-select").addEventListener("change", function() {
                                    var url = this.value;
                                    if (url) {
                                        window.location.href = url;
                                    }
                                     });
                        </script>
 

{% endblock body %}
    