blog/urls.py
from django.urls import path
from . import views

# api
from . import api


app_name='blog'

urlpatterns = [
    path('',views.post_list,name='post-list'),
    path('<slug:slug>',views.post_detail,name='post-detail'),

    # api url
    path('postapi/api',api.PostApi.as_view()),
    path('postapi/<int:pk>',api.PostDetailApi.as_view()),
    path('postall/all/<int:pk>',api.PostAllApi.as_view()),
   
]

job/urls.py
from django.urls import path
from . import views
from . import api



app_name= 'job'

urlpatterns = [

     # api

    path('jobs_api/all',api.JobApi.as_view()),
    path('job_api/<int:pk>',api.JobDetailApi.as_view()),


    path('',views.job_list,name='job-list'),
   
    path('<slug:slug>/',views.job_detail,name='job-detail'),

     path('add_job',views.add_job,name='add-job'),

    

    
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
...
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)



urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('',include('settings.urls')),


    path('blog/',include('blog.urls')),

    path('job/',include('job.urls')),

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),



    path('summernote/', include('django_summernote.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from taggit.managers import TaggableManager

from django.contrib.auth.models import User
from django.utils import timezone
from django.utils.text import slugify




class Post(models.Model):
    user=models.ForeignKey(User,related_name='post_user',on_delete=models.CASCADE)
    title=models.CharField(max_length=120)
    content=models.TextField(max_length=3500)
    image=models.ImageField(upload_to='photo_post')
    draft=models.BooleanField(default=True)
    tags = TaggableManager()
    slug=models.SlugField(null=True,blank=True)
    publish_date=models.DateTimeField(default=timezone.now)
    category=models.ForeignKey('Category',related_name='post_category',on_delete=models.SET_NULL,null=True,blank=True)

    def __str__(self):
        return self.title
    
    def save(self,*args,**kwargs):
        self.slug=slugify(self.title)
        super(Post,self).save(*args,**kwargs)


class Category(models.Model):
    name=models.CharField(max_length=120)

    def __str__(self):
        return self.name

class Review(models.Model):
    user=models.CharField(max_length=120)
    post=models.ForeignKey(Post,related_name='review_post',on_delete=models.CASCADE)
    publish_date=models.DateTimeField(default=timezone.now)
    content=models.TextField(max_length=1500)
    rate=models.IntegerField(choices=[(i,i) for i in range(1,6)])

    def __str__(self):
        return str(self.post)

blog/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model=Review
        # fields='__all__'
        exclude=('post','publish_date')

blog/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator

from .models import Post,Category,Review
from .forms import ReviewForm


def post_list(request):

    posts=Post.objects.all().prefetch_related('review_post').order_by('-id')

    category=Category.objects.all().prefetch_related('post_category').order_by('-id')[:5]

    title=request.GET.get('search_name')
    if title:
        posts=posts.filter(title__icontains=title)
    else:
        posts=posts
    
    category_id=request.GET.get('category_id')
    if category_id:
        posts=posts.filter(category_id=category_id)


    paginator = Paginator(posts, 10)  # Show 25 contacts per page.

    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context={
        'posts':page_obj,
        'category':category
    }

    return render(request,'blog/post_list.html',context)



def post_detail(request,slug):
    post=Post.objects.get(slug=slug)

    title=request.GET.get('search_name')
    if title:
        search=Post.objects.filter(title_icontains=title)
    else:
        search=Post.objects.all()

    previous_post=Post.objects.filter(id__lt=post.id).order_by('-id').first()
    next_post=Post.objects.filter(id__gt=post.id).order_by('id').first()

    reviews=Review.objects.filter(post=post)

    if request.method =='POST':
        form=ReviewForm(request.POST)
        if form.is_valid():
            myform=form.save(commit=False)
            myform.post=post
            myform.save()
            return redirect(f'/blog/{slug}')
    else:
        form=ReviewForm()

    category=Category.objects.all().prefetch_related('post_category')[:5]

   

    
    context={
        'post':post,
        'previous_post':previous_post,
        'next_post':next_post,
        'reviews':reviews,
        'form':form,
        'category':category,
        
        
    }
    return render(request,'blog/post_detail.html',context)

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}

{% block body %}
     <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
      <div class="container">
          <div class="row">
              <div class="col-xl-12">
                  <div class="bradcam_text">
                      <h3>single blog</h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
  <!--/ bradcam_area  -->

   <!--================Blog Area =================-->
   <section class="blog_area single-post-area section-padding">
      <div class="container">
         <div class="row">
            <div class="col-lg-8 posts-list">
               <div class="single-post">
                  <div class="feature-img">
                     <img class="img-fluid" src="{{post.image.url}}" alt="">
                  </div>
                  <div class="blog_details">
                     <h2>{{post.title}}
                     </h2>
                     <ul class="blog-info-link mt-3 mb-4">
                        <li><a href="#"><i class="fa fa-user"></i> 
                        {% for tag in post.tags.all %}
                            {{tag.name}}
                        {% endfor %}

                         
                            </a></li>
                        <li><a href="#"><i class="fa fa-comments"></i> {{reviews.count}} Comments</a></li>
                     </ul>
                    
                     <p class="excert">
                       {{post.content|truncatewords:50|safe}}
                     </p>
                    
                  </div>
               </div>
               <div class="navigation-top">
            
                  <div class="navigation-area">
                     <div class="row">
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                           <div class="thumb">
                              <a href="#">
                                 <img class="img-fluid" src="img/post/preview.png" alt="">
                              </a>
                           </div>
                           <div class="arrow">
                              <a href="#">
                                 <span class="lnr text-white ti-arrow-left"></span>
                              </a>
                           </div>
                           <div class="detials">
                              <p>Prev Post</p>
                              {% if previous_post %}
                                    <a href="{% url 'blog:post-detail' previous_post.slug %}">
                                  
                                          <h4>{{previous_post.title}}</h4>
                                    </a>   
                                {% endif %}
                           
                           </div>
                        </div>
                        <div
                           class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                           <div class="detials">
                              <p>Next Post</p>
                            
                            {% if next_post %}
                                  <a href="{% url 'blog:post-detail' next_post.slug %}">
                                     <h4>{{next_post.title}}</h4>
                                  </a>
                            {% endif %}
                                
                            
                           </div>
                           <div class="arrow">
                              <a href="#">
                                 <span class="lnr text-white ti-arrow-right"></span>
                              </a>
                           </div>
                           <div class="thumb">
                              <a href="#">
                                 <img class="img-fluid" src="img/post/next.png" alt="">
                              </a>
                           </div>
                        </div>
                     </div>
                  </div>
               </div>
             
               <div class="comments-area">
                  <h4>({{reviews.count}}) Comments</h4>

                
                {% for object in reviews %}
                  <div class="comment-list">
                     <div class="single-comment justify-content-between d-flex">
                        <div class="user justify-content-between d-flex">
                           <div class="thumb">
                              <img src="img/comment/comment_1.png" alt="">
                           </div>
                           <div class="desc">
                              <p class="comment">
                                 {{object.content|truncatewords:35}}
                              </p>
                              <div class="d-flex justify-content-between">
                                 <div class="d-flex align-items-center">
                                    <h5>
                                       <a href="#">{{object.user}} </a>
                                    </h5>
                                    <p class="date">{{object.publish_date|date:'D-M-Y'}}</p>
                                 </div>
                                 <div class="reply-btn">
                                    <a href="#" class="btn-reply text-uppercase">reply</a>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>  
                  {% empty %} 
                  <h4>Sorry There Are No Any Comments</h4>
                {% endfor %}
                    
                 
                 
               </div>
               <div class="comment-form">
                  <h4>Leave a Reply</h4>
                  <form class="form-contact comment_form" action="#" id="commentForm" method="post">
                     
                        {% csrf_token %}
                        {% bootstrap_form form %}
                    
                     <div class="form-group">
                        <button type="submit" class="button button-contactForm btn_1 boxed-btn">Send Message</button>
                     </div>
                  </form>
               </div>
            </div>
            <div class="col-lg-4">
               <div class="blog_right_sidebar">
                  <aside class="single_sidebar_widget search_widget">
                     <form action="/blog/" method="get">
                        <div class="form-group">
                           <div class="input-group mb-3">
                              <input type="text" class="form-control" placeholder='Search Keyword'
                                 onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'" name="'search_name">
                              <div class="input-group-append">
                                 <button class="btn" type="button"><i class="ti-search"></i></button>
                              </div>
                           </div>
                        </div>
                        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                           type="submit">Search</button>
                     </form>
                  </aside>
                  <aside class="single_sidebar_widget post_category_widget">
                     <h4 class="widget_title">Category</h4>
                     <ul class="list cat-list">

                
                {% for object in category %}
                    
               
                    
                        <li>
                           <a href="#" class="d-flex">
                              <p>{{object.name}}</p>
                              <p>({{object.post_category.count}})</p>
                           </a>
                        </li>

                         {% endfor %}
                    
                     </ul>
                  </aside>
                  <aside class="single_sidebar_widget popular_post_widget">
                     <h3 class="widget_title">Recent Post</h3>
                     <div class="media post_item">
                        <img src="img/post/post_1.png" alt="post">
                        <div class="media-body">
                           <a href="single-blog.html">
                              <h3>From life was you fish...</h3>
                           </a>
                           <p>January 12, 2019</p>
                        </div>
                     </div>
                     <div class="media post_item">
                        <img src="img/post/post_2.png" alt="post">
                        <div class="media-body">
                           <a href="single-blog.html">
                              <h3>The Amazing Hubble</h3>
                           </a>
                           <p>02 Hours ago</p>
                        </div>
                     </div>
                     <div class="media post_item">
                        <img src="img/post/post_3.png" alt="post">
                        <div class="media-body">
                           <a href="single-blog.html">
                              <h3>Astronomy Or Astrology</h3>
                           </a>
                           <p>03 Hours ago</p>
                        </div>
                     </div>
                     <div class="media post_item">
                        <img src="img/post/post_4.png" alt="post">
                        <div class="media-body">
                           <a href="single-blog.html">
                              <h3>Asteroids telescope</h3>
                           </a>
                           <p>01 Hours ago</p>
                        </div>
                     </div>
                  </aside>
                  <aside class="single_sidebar_widget tag_cloud_widget">
                     <h4 class="widget_title">Tag Clouds</h4>
                     <ul class="list">
                        <li>
                           <a href="#">project</a>
                        </li>
                        <li>
                           <a href="#">love</a>
                        </li>
                        <li>
                           <a href="#">technology</a>
                        </li>
                        <li>
                           <a href="#">travel</a>
                        </li>
                        <li>
                           <a href="#">restaurant</a>
                        </li>
                        <li>
                           <a href="#">life style</a>
                        </li>
                        <li>
                           <a href="#">design</a>
                        </li>
                        <li>
                           <a href="#">illustration</a>
                        </li>
                     </ul>
                  </aside>
                  <aside class="single_sidebar_widget instagram_feeds">
                     <h4 class="widget_title">Instagram Feeds</h4>
                     <ul class="instagram_row flex-wrap">
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_5.png" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_6.png" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_7.png" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_8.png" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_9.png" alt="">
                           </a>
                        </li>
                        <li>
                           <a href="#">
                              <img class="img-fluid" src="img/post/post_10.png" alt="">
                           </a>
                        </li>
                     </ul>
                  </aside>
                  <aside class="single_sidebar_widget newsletter_widget">
                     <h4 class="widget_title">Newsletter</h4>
                     <form action="#">
                        <div class="form-group">
                           <input type="email" class="form-control" onfocus="this.placeholder = ''"
                              onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                        </div>
                        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                           type="submit">Subscribe</button>
                     </form>
                  </aside>
               </div>
            </div>
         </div>
      </div>
   </section>
   <!--================ Blog Area end =================-->
{% endblock body %}
    

blog/templates/blog/post_list.html
{% extends 'base.html' %}


{% block body %}
     <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>blog</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->


    <!--================Blog Area =================-->
    <section class="blog_area section-padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mb-5 mb-lg-0">
                    <div class="blog_left_sidebar">

                    
                    {% for object in posts %}
                        
                    <article class="blog_item">
                            <div class="blog_item_img">
                                <img class="card-img rounded-0" src="{{object.image.url}}" alt="" style="width: 350px; height: auto;">
                                <a href="#" class="blog_item_date">
                                    <h3>{{object.publish_date|date:'d'}}</h3>
                                    <p>{{object.publish_date|date:'M'}}</p>
                                </a>
                            </div>

                            <div class="blog_details">
                                <a class="d-inline-block" href="{% url 'blog:post-detail' object.slug %}">
                                    <h2>{{object.title}}</h2>
                                </a>
                                <p>{{object.content|truncatewords:25|safe}}</p>
                                <ul class="blog-info-link">
                                    <li><a href="#"><i class="fa fa-user"></i> 
                                    {% for tag in object.tags.all %}
                                        {{tag.name}}
                                    {% endfor %}
                                        </a></li>
                                    <li><a href="#"><i class="fa fa-comments"></i> {{object.review_post.count}} Comments</a></li>
                                </ul>
                            </div>
                    </article>
                    {% endfor %}

                    
                    
                    {% if posts.has_other_pages %}
                        
                  
                        <nav class="blog-pagination justify-content-center d-flex">
                            <ul class="pagination">

                         
                         {% if posts.has_previous %}
                            
                         
                            
                                
                                <li class="page-item">
                                    <a href="?page={{posts.previous_page_number}}" class="page-link" aria-label="Previous">
                                        <i class="ti-angle-left"></i>
                                    </a>
                                </li>

                                {% endif %}

                            
                     
                   {% for i in posts.paginator.page_range %}
                        {% if i >= posts.number|add:'-3' and i <= posts.number|add:'3' %}
                            <li class="page-item {% if i == posts.number %}active{% endif %}">
                                <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                            </li>
                        {% endif %}
               {% endfor %}
                             

                            
                            {% if posts.has_next %}
                                
                        
                                
                                <li class="page-item">
                                    <a href="?page={{post.next_page_number}}" class="page-link" aria-label="Next">
                                        <i class="ti-angle-right"></i>
                                    </a>
                                </li>

                                {% endif %}



                            </ul>
                        </nav>

                          {% endif %}


                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="blog_right_sidebar">
                        <aside class="single_sidebar_widget search_widget">
                            <form action="{% url 'blog:post-list' %}" method="get">
                                <div class="form-group">
                                    <div class="input-group mb-3">
                                        <input type="text" class="form-control" placeholder='Search Keyword'
                                            onfocus="this.placeholder = ''"
                                            onblur="this.placeholder = 'Search Keyword'" name="search_name">
                                        <div class="input-group-append">
                                            <button class="btn" type="button"><i class="ti-search"></i></button>
                                        </div>
                                    </div>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Search</button>
                            </form>
                        </aside>

                        <aside class="single_sidebar_widget post_category_widget">
                            <h4 class="widget_title">Category</h4>
                            <ul class="list cat-list">

                            
                            {% for object in category %}
                               
                                <li>
                                    <a href="?category_id={{object.id}}" class="d-flex">
                                        <p>{{object}}</p>
                                        <p>({{object.post_category.count}})</p>
                                    </a>
                                </li>
                             {% endfor %}
                               
                            </ul>
                        </aside>

                        <aside class="single_sidebar_widget popular_post_widget">
                            <h3 class="widget_title">Recent Post</h3>
                        
                        {% for object in posts %}
                             <div class="media post_item">
                                <img src="{{object.image.url}}" alt="post" style="width: 80px; height: auto;" >
                                <div class="media-body">
                                    <a href="{% url 'blog:post-detail' object.slug %}">
                                        <h3>{{object.title}}</h3>
                                    </a>
                                    <p>{{object.publish_date|date:'D-M-Y'}}</p>
                                </div>
                            </div>
                           {% endfor %}
                          
                        </aside>
                        <aside class="single_sidebar_widget tag_cloud_widget">
                            <h4 class="widget_title">Tag Clouds</h4>
                            <ul class="list">
                                <li>
                                    <a href="#">project</a>
                                </li>
                                <li>
                                    <a href="#">love</a>
                                </li>
                                <li>
                                    <a href="#">technology</a>
                                </li>
                                <li>
                                    <a href="#">travel</a>
                                </li>
                                <li>
                                    <a href="#">restaurant</a>
                                </li>
                                <li>
                                    <a href="#">life style</a>
                                </li>
                                <li>
                                    <a href="#">design</a>
                                </li>
                                <li>
                                    <a href="#">illustration</a>
                                </li>
                            </ul>
                        </aside>


                        <aside class="single_sidebar_widget instagram_feeds">
                            <h4 class="widget_title">Instagram Feeds</h4>
                            <ul class="instagram_row flex-wrap">
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_5.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_6.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_7.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_8.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_9.png" alt="">
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        <img class="img-fluid" src="img/post/post_10.png" alt="">
                                    </a>
                                </li>
                            </ul>
                        </aside>


                        <aside class="single_sidebar_widget newsletter_widget">
                            <h4 class="widget_title">Newsletter</h4>

                            <form action="#">
                                <div class="form-group">
                                    <input type="email" class="form-control" onfocus="this.placeholder = ''"
                                        onblur="this.placeholder = 'Enter email'" placeholder='Enter email' required>
                                </div>
                                <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"
                                    type="submit">Subscribe</button>
                            </form>
                        </aside>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================Blog Area =================-->

{% endblock body %}
    