job/urls.py
from django.urls import path
from . import views
from . import api



app_name= 'job'

urlpatterns = [

     # api

    path('jobs_api/all',api.JobApi.as_view()),
    path('job_api/<int:pk>',api.JobDetailApi.as_view()),


    path('',views.job_list,name='job-list'),
   
    path('<slug:slug>/',views.job_detail,name='job-detail'),

     path('add_job',views.add_job,name='add-job'),

    

    
   
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
...
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

...

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)



urlpatterns = [
    path('accounts/',include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('',include('settings.urls')),


    path('blog/',include('blog.urls')),

    path('job/',include('job.urls')),

    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),



    path('summernote/', include('django_summernote.urls')),
    
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Job Board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- <link rel="manifest" href="site.webmanifest"> -->
    <link rel="shortcut icon" type="image/x-icon" href="img/favicon.png">
    <!-- Place favicon.ico in the root directory -->

    <!-- CSS here -->
    <link rel="stylesheet" href="{% static 'en/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/magnific-popup.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/nice-select.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/gijgo.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'en/css/slicknav.css' %}">

    <link rel="stylesheet" href="{% static 'en/css/style.css' %}">

    <!-- <link rel="stylesheet" href="css/responsive.css"> -->
</head>

<body>
    <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        <![endif]-->

    <!-- header-start -->
    <header>
        <div class="header-area ">
            <div id="sticky-header" class="main-header-area">
                <div class="container-fluid ">
                    <div class="header_bottom_border">
                        <div class="row align-items-center">
                            <div class="col-xl-3 col-lg-2">
                                <div class="logo">
                                    <a href="index.html">
                                        <img src="img/logo.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="col-xl-6 col-lg-7">
                                <div class="main-menu  d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="/">home</a></li>
                                            <li><a href="/job/">Browse Job</a></li>
                                            <li><a href="">pages <i class="ti-angle-down"></i></a>
                                                <ul class="submenu">
                                                    <li><a href="/accounts/candidator">Candidates </a></li>
                                                    
                                                </ul>
                                            </li>
                                            <li><a href="/blog/">blog </i></a>
                                             
                                            </li>
                                            <li><a href="/accounts/contact">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                            <div class="col-xl-3 col-lg-3 d-none d-lg-block">
                                <div class="Appointment">

                                    
                                    {% if user.is_authenticated %}
                                        <div class="phone_num d-none d-xl-block">
                                                
                                                <a href="/accounts/signup">Signup</a>
                                        </div>
                                            <div class="d-none d-lg-block">
                                                <a class="boxed-btn3" href="{% url 'job:add-job' %}">Post a Job</a>
                                            </div> 
                                        {% else %}
                                         <div class="phone_num d-none d-xl-block">
                                                <a href="/accounts/login">Log in</a>

                                         </div>

                                    {% endif %}
                                        
                                   
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </header>
    <!-- header-end -->

  


    
   
        



    
    {% block body %}
        
    {% endblock body %}
        














    
    <!-- footer start -->
    <footer class="footer">
        <div class="footer_top">
            <div class="container">
                <div class="row">
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                            <div class="footer_logo">
                                <a href="#">
                                    <img src="{{data.image.url}}" alt="" style="width: 80px; height: auto;">
                                </a>
                            </div>
                            <p>
                                {{data.email}} <br>
                                +{{data.phone}}<br>
                                {{data.address}}
                            </p>
                            <div class="socail_links">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="ti-facebook"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-google-plus"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fa fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>

                        </div>
                    </div>
                    <div class="col-xl-2 col-md-6 col-lg-2">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.1s" data-wow-delay=".4s">
                            <h3 class="footer_title">
                                Company
                            </h3>
                            <ul>
                                <li><a href="#">About </a></li>
                                <li><a href="#"> Pricing</a></li>
                                <li><a href="#">Carrier Tips</a></li>
                                <li><a href="#">FAQ</a></li>
                            </ul>

                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 col-lg-3">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.2s" data-wow-delay=".5s">
                            <h3 class="footer_title">
                                Category
                            </h3>
                            <ul>
                                <li><a href="#">Design & Art</a></li>
                                <li><a href="#">Engineering</a></li>
                                <li><a href="#">Sales & Marketing</a></li>
                                <li><a href="#">Finance</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xl-4 col-md-6 col-lg-4">
                        <div class="footer_widget wow fadeInUp" data-wow-duration="1.3s" data-wow-delay=".6s">
                            <h3 class="footer_title">
                                Subscribe
                            </h3>
                            <form action="#" class="newsletter_form">
                                <input type="text" placeholder="Enter your mail">
                                <button type="submit">Subscribe</button>
                            </form>
                            <p class="newsletter_text">Esteem spirit temper too say adieus who direct esteem esteems
                                luckily.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy-right_text wow fadeInUp" data-wow-duration="1.4s" data-wow-delay=".3s">
            <div class="container">
                <div class="footer_border"></div>
                <div class="row">
                    <div class="col-xl-12">
                        <p class="copy_right text-center">
                            <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--/ footer end  -->

    <!-- link that opens popup -->
    <!-- JS here -->
    <script src="{% static 'en/js/vendor/modernizr-3.5.0.min.js' %}"></script>
    <script src="{% static 'en/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script src="{% static 'en/js/popper.min.js' %}"></script>
    <script src="{% static 'en/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'en/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'en/js/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'en/js/ajax-form.js' %}"></script>
    <script src="{% static 'en/js/waypoints.min.js' %}"></script>
    <script src="{% static 'en/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'en/js/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'en/js/scrollIt.js' %}"></script>
    <script src="{% static 'en/js/jquery.scrollUp.min.js' %}"></script>
    <script src="{% static 'en/js/wow.min.js' %}"></script>
    <script src="{% static 'en/js/nice-select.min.js' %}"></script>
    <script src="{% static 'en/js/jquery.slicknav.min.js' %}"></script>
    <script src="{% static 'en/js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'en/js/plugins.js' %}"></script>
    <script src="{% static 'en/js/gijgo.min.js' %}"></script>



    <!--contact js-->
    <script src="{% static 'en/js/contact.js' %}"></script>
    <script src="{% static 'en/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'en/js/jquery.form.js' %}"></script>
    <script src="{% static 'en/js/jquery.validate.min.js' %}"></script>
    <script src="{% static 'en/js/mail-script.js' %}"></script>


    <script src="{% static 'en/js/main.js' %}"></script>

</body>

</html>